development:
  adapter: postgresql
  encoding: unicode
  database: message_me_db
  pool: 5
  host: localhost
  username: Stetson
  password:

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: database_name_test
#   pool: 5
#   username: postgres_user_name
#   password: postgres_password

# staging:
#   url: <%= ENV['DATABASE_URL'] %>

# production:
#   url: <%= ENV['DATABASE_URL'] %> 